### ISSUE TITLE
No module named 'music_metadata'

### ISSUE THREAD

**Issue by kiddhustle** [matijakolaric-com/django-music-publisher#63]
**Describe the bug**
Running the app I see an error which says the following:

```
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'music_publisher.templatetags.cwr_filters': No module named 'music_metadata'
```

I checked the template tag on question and I can see where `music_metadata` imported, but I can't see where it is defined.

music_publisher/templatetags/cwr_filters.py 

```
from music_publisher import models
from music_metadata.territories.territory import Territory
```

Is it part of this codebase or is it an external dependancy.

**Version and deployment**
```
python = "^3.10"
django = "4.1.13"
django-music-publisher = "^23.4"
```

**To Reproduce**
1. Install the app in a Django project

**Expected behavior**
1. App to run without an error

**Screenshots**

**Logs**
```
python manage.py runserver_plus 8001
Traceback (most recent call last):
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/utils.py", line 69, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/backends/django.py", line 128, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/music_publisher/templatetags/cwr_filters.py", line 10, in <module>
    from music_metadata.territories.territory import Territory
ModuleNotFoundError: No module named 'music_metadata'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "$HOME/workspace/syncedin/manage.py", line 22, in <module>
    main()
  File "$HOME/workspace/syncedin/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/music_publisher/models.py", line 35, in <module>
    from .cwr_templates import (
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/music_publisher/cwr_templates.py", line 13, in <module>
    "HDR": Template(
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/base.py", line 147, in __init__
    engine = Engine.get_default()
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/engine.py", line 107, in get_default
    for engine in engines.all():
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/utils.py", line 94, in all
    return [self[alias] for alias in self]
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/utils.py", line 94, in <listcomp>
    return [self[alias] for alias in self]
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/utils.py", line 85, in __getitem__
    engine = engine_cls(params)
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/backends/django.py", line 24, in __init__
    options["libraries"] = self.get_templatetag_libraries(libraries)
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/backends/django.py", line 42, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/backends/django.py", line 116, in get_installed_libraries
    return {
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/backends/django.py", line 116, in <dictcomp>
    return {
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/backends/django.py", line 105, in get_template_tag_modules
    for name in get_package_libraries(pkg):
  File "$HOME/.virtualenvs/syncedin/lib/python3.10/site-packages/django/template/backends/django.py", line 130, in get_package_libraries
    raise InvalidTemplateLibrary(
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'music_publisher.templatetags.cwr_filters': No module named 'music_metadata'
```

**Additional context**

**Comment by matijakolaric** [comment]
Not able to reproduce
